# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          branch: 'master'
          owner: 'TopchetoEU'
          repository: 'java-jscript'
      - name: Build
        run: |
          cd java-jscript; gradle build